apiVersion: v1
data:
  connection_string: WyctLWNvbm5lY3Rpb24nLCAncG9zdGdyZXM6Ly90YWtlb25hZG1pbjphVmVyeVNlY3VyZVBhc3N3b3JkMTIzIUB0YWtlb25kZXZkYi5jeWphZXB6cHgxdGsuZXUtd2VzdC0yLnJkcy5hbWF6b25hd3MuY29tL3Rha2VvbmRldmRiJywgJy0tc2NoZW1hJywgJ2RldjAxJywgJy1qJywgJy1hJywgJy0td2F0Y2gnXQo=
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"connection_string":"WyctLWNvbm5lY3Rpb24nLCAncG9zdGdyZXM6Ly90YWtlb25hZG1pbjphVmVyeVNlY3VyZVBhc3N3b3JkMTIzIUB0YWtlb25kZXZkYi5jeWphZXB6cHgxdGsuZXUtd2VzdC0yLnJkcy5hbWF6b25hd3MuY29tL3Rha2VvbmRldmRiJywgJy0tc2NoZW1hJywgJ2RldjAxJywgJy1qJywgJy1hJywgJy0td2F0Y2gnXQo="},"kind":"Secret","metadata":{"annotations":{},"name":"gql-connection-string","namespace":"takeon-dev-test"},"type":"Opaque"}
  creationTimestamp: "2020-01-24T15:00:15Z"
  name: gql-connection-string
  namespace: takeon-dev-test
  resourceVersion: "12092005"
  selfLink: /api/v1/namespaces/takeon-dev-test/secrets/gql-connection-string
  uid: 3a6c5ba4-3eba-11ea-9c2e-0a5091216e02
type: Opaque
