apiVersion: v1
data:
  connection-string: WyctLWNvbm5lY3Rpb24nLCAncG9zdGdyZXM6Ly90YWtlb25hZG1pbjphVmVyeVNlY3VyZVBhc3N3b3JkMTIzIUB0YWtlb25kZXYuY3I2Z2Vwc3QxeXJpLmV1LXdlc3QtMi5yZHMuYW1hem9uYXdzLmNvbS90YWtlb25kZXYnLCAnLS1zY2hlbWEnLCAnZGV2MDEnLCAnLWonLCAnLWEnLCAnLS13YXRjaCdd
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"connection-string":"WyctLWNvbm5lY3Rpb24nLCAncG9zdGdyZXM6Ly90YWtlb25hZG1pbjphVmVyeVNlY3VyZVBhc3N3b3JkMTIzIUB0YWtlb25kZXYuY3I2Z2Vwc3QxeXJpLmV1LXdlc3QtMi5yZHMuYW1hem9uYXdzLmNvbS90YWtlb25kZXYnLCAnLS1zY2hlbWEnLCAnZGV2MDEnLCAnLWonLCAnLWEnLCAnLS13YXRjaCdd"},"kind":"Secret","metadata":{"annotations":{},"name":"gql-connection-string","namespace":"takeon-dev-sandbox-test"},"type":"Opaque"}
  creationTimestamp: "2020-03-16T10:37:11Z"
  name: gql-connection-string
  namespace: takeon-dev-sandbox-test
  resourceVersion: "6393"
  selfLink: /api/v1/namespaces/takeon-dev-sandbox-test/secrets/gql-connection-string
  uid: 17f7e5ae-6772-11ea-8273-06bc6e567ffe
type: Opaque
