apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: ${namespace}
  name: takeon-ui
  labels:
    app: takeon-ui
spec:
  replicas: 1
  template:
    metadata:
      namespace: ${namespace}
      labels:
        app: takeon-ui
    spec:
      containers:
      - name: takeon-ui
        image: 014669633018.dkr.ecr.eu-west-2.amazonaws.com/takeon-dev-ui:${namespace}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 5000
          protocol: TCP