apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: api-access-${file(config.json):namespace}
  namespace: ${file(config.json):namespace}
rules:
  -
    apiGroups:
      - ""
    resources:
      - services
      - endpoints
    verbs: ["*"]
  - nonResourceURLs: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: api-access-${file(config.json):namespace}
  namespace: ${file(config.json):namespace}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: api-access-${file(config.json):namespace}
subjects:
- kind: ServiceAccount
  name: default
  namespace: ${file(config.json):namespace}
