apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ${file(config.json):namespace}
  name: graphql
  labels:
    app: graphql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphql
  template:
    metadata:
      namespace: ${file(config.json):namespace}
      labels:
        app: graphql
    spec:
      containers:
      - name: graphql
        image: 226575302242.dkr.ecr.eu-west-2.amazonaws.com/takeon-dev-sandbox-graphql:latest
        imagePullPolicy: Always
        args: ${connection_string}
        ports:
        - containerPort: 5000
---


apiVersion: v1
kind: Service
metadata:
  name: graphql
  namespace: ${file(config.json):namespace}
  labels:
    app: graphql
spec:
  ports:
  - port: 5001
    targetPort: 5000
    protocol: TCP
  selector:
    app: graphql
  type: ClusterIP
