apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: ${namespace}
  name: takeon-ui
  labels:
    app: takeon-ui
spec:
  replicas: 1
  template:
    metadata:
      namespace: ${namespace}
      labels:
        app: takeon-ui
    spec:
      containers:
      - name: takeon-ui
        image: 014669633018.dkr.ecr.eu-west-2.amazonaws.com/takeon-dev-ui:${namespace}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 5000
          protocol: TCP
        env:
          - name: API_URL
	          valueFrom:
	            secretKeyRef:
		            name: validation-trigger-api
                key: validation-trigger-API-URL
	        - name: API_KEY
	          valueFrom:
	             secretKeyRef:
		             name: validation-trigger-api
		             key: API-key
---

apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  name: takeon-ui
  namespace: ${namespace}
  labels:
    app: takeon-ui
spec:
  ports:
  - port: 5001
    name: flask
    targetPort: 5000
    protocol: TCP
  - port: 8080
    name: http
    targetPort: 5000
    protocol: TCP
  selector:
    app: takeon-ui
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 10.0.0.0/24
  - 10.0.1.0/24
  - 80.5.92.42/32
  - 89.248.28.81/32
  - 194.34.204.37/32
