apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: takeon-dev
  name: graphql
  labels:
    app: graphql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphql
  template:
    metadata:
      namespace: takeon-dev
      labels:
        app: graphql
    spec:
      containers:
      - name: graphql
        image: graphile/postgraphile
        args: ['--connection', 'postgres://takeonadmin:aVerySecurePassword123!@validationdb.cyjaepzpx1tk.eu-west-2.rds.amazonaws.com/validationdb', '--schema', 'dev01', '-j', '-a', '--watch']
        ports:
        - containerPort: 5000
---


apiVersion: v1
kind: Service
metadata:
  name: graphql
  labels:
    app: graphql
spec:
  ports:
  - port: 5001
    targetPort: 5000
    protocol: TCP
  selector:
    app: graphql
  type: ClusterIP
